openapi: 3.0.3
info:
  title: API Auctions
  version: 1.0.0
  description: Auctios web
paths:
  /subastas/:
    get:
      operationId: subastas_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedAuctionListCreateList'
          description: ''
    post:
      operationId: subastas_create
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuctionListCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuctionListCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuctionListCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionListCreate'
          description: ''
  /subastas/{auction_id}/pujas/:
    get:
      operationId: subastas_pujas_list
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedBidList'
          description: ''
    post:
      operationId: subastas_pujas_create
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bid'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bid'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bid'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
          description: ''
  /subastas/{auction_id}/pujas/{id}/:
    get:
      operationId: subastas_pujas_retrieve
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
          description: ''
    put:
      operationId: subastas_pujas_update
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bid'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bid'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bid'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
          description: ''
    patch:
      operationId: subastas_pujas_partial_update
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBid'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBid'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBid'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
          description: ''
    delete:
      operationId: subastas_pujas_destroy
      parameters:
      - in: path
        name: auction_id
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /subastas/{id}/:
    get:
      operationId: subastas_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    put:
      operationId: subastas_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuctionDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AuctionDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AuctionDetail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    patch:
      operationId: subastas_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedAuctionDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedAuctionDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedAuctionDetail'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuctionDetail'
          description: ''
    delete:
      operationId: subastas_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /subastas/categoria/{id}/:
    get:
      operationId: subastas_categoria_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetail'
          description: ''
    put:
      operationId: subastas_categoria_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CategoryDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CategoryDetail'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetail'
          description: ''
    patch:
      operationId: subastas_categoria_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCategoryDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCategoryDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCategoryDetail'
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryDetail'
          description: ''
    delete:
      operationId: subastas_categoria_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /subastas/categorias/:
    get:
      operationId: subastas_categorias_list
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - subastas
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCategoryListCreateList'
          description: ''
    post:
      operationId: subastas_categorias_create
      tags:
      - subastas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryListCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CategoryListCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CategoryListCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryListCreate'
          description: ''
components:
  schemas:
    AuctionDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        creation_date:
          type: string
          format: date-time
          readOnly: true
        closing_date:
          type: string
          format: date-time
        isOpen:
          type: boolean
          readOnly: true
        title:
          type: string
          maxLength: 150
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: 1
          format: int64
        brand:
          type: string
          maxLength: 100
        thumbnail:
          type: string
          format: uri
          maxLength: 200
        category:
          type: integer
      required:
      - brand
      - category
      - closing_date
      - creation_date
      - description
      - id
      - isOpen
      - price
      - rating
      - stock
      - thumbnail
      - title
    AuctionListCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        creation_date:
          type: string
          format: date-time
          readOnly: true
        closing_date:
          type: string
          format: date-time
        isOpen:
          type: boolean
          readOnly: true
        title:
          type: string
          maxLength: 150
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: 1
          format: int64
        brand:
          type: string
          maxLength: 100
        thumbnail:
          type: string
          format: uri
          maxLength: 200
        category:
          type: integer
      required:
      - brand
      - category
      - closing_date
      - creation_date
      - description
      - id
      - isOpen
      - price
      - rating
      - stock
      - thumbnail
      - title
    Bid:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        timestamp:
          type: string
          format: date-time
          readOnly: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        bidder:
          type: string
          maxLength: 100
        auction:
          type: integer
      required:
      - amount
      - auction
      - bidder
      - id
      - timestamp
    CategoryDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
      required:
      - id
      - name
    CategoryListCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
      required:
      - id
      - name
    PaginatedAuctionListCreateList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/AuctionListCreate'
    PaginatedBidList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Bid'
    PaginatedCategoryListCreateList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/CategoryListCreate'
    PatchedAuctionDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        creation_date:
          type: string
          format: date-time
          readOnly: true
        closing_date:
          type: string
          format: date-time
        isOpen:
          type: boolean
          readOnly: true
        title:
          type: string
          maxLength: 150
        description:
          type: string
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        rating:
          type: string
          format: decimal
          pattern: ^-?\d{0,1}(?:\.\d{0,2})?$
        stock:
          type: integer
          maximum: 9223372036854775807
          minimum: 1
          format: int64
        brand:
          type: string
          maxLength: 100
        thumbnail:
          type: string
          format: uri
          maxLength: 200
        category:
          type: integer
    PatchedBid:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        timestamp:
          type: string
          format: date-time
          readOnly: true
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        bidder:
          type: string
          maxLength: 100
        auction:
          type: integer
    PatchedCategoryDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
